#!/usr/bin/perl -w

use strict;
my $command="/Users/catherineanderson/SuiteMSA_Package1.2.02/clustalw-2.1-macosx/clustalw2  -INFILE=/Users/catherineanderson/DataBaseProject/ANID_06160_ortho_group.fasta -OUTPUT=FASTA -OUTFILE=/Users/catherineanderson/DataBaseProject/ANID_06160_ortho_group_CLTW2 -QUIET 2> clustalW_log.txt";
system($command);
print "\nCOMMAND EXECUTED\n\n";