#!/usr/bin/perl -w

use strict;
my $command="/Users/catherineanderson/OtherAlignmentPrograms/muscle3.8.31_i86darwin64 -in /Users/catherineanderson/DataBaseProject/ANID_06160_ortho_group.fasta -out /Users/catherineanderson/DataBaseProject//ANID_06160_ortho_group_Muscle -quiet 2> muscle_log.txt";
system($command);
print "\nCOMMAND EXECUTED\n\n";