#! /bin/bash

./collectdata.py Anoura_latidens 6 1
./collectdata.py Antrozous_pallidus 11 34
./collectdata.py Arielulus_aureocollaris 5 7
./collectdata.py Arielulus_circumdatus 7 3
./collectdata.py Artibeus_amplus 32 17
./collectdata.py Artibeus_anderseni 14 11
./collectdata.py Artibeus_aztecus 11 4
./collectdata.py Artibeus_cinereus 173 92
./collectdata.py Artibeus_concolor 92 99
./collectdata.py Artibeus_fimbriatus 3 10
./collectdata.py Artibeus_hartii 3 19
./collectdata.py Artibeus_jamaicensis_49 9 8
./collectdata.py Artibeus_jamaicensis_50 37 21
./collectdata.py Artibeus_jamaicensis_51 8 2
./collectdata.py Artibeus_lituratus 642 79
./collectdata.py Artibeus_obscurus 576 57
./collectdata.py Artibeus_phaeotis 62 28
./collectdata.py Artibeus_planirostris 562 82
./collectdata.py Artibeus_toltecus 27 15
./collectdata.py Aselliscus_stoliczkanus 57 122
./collectdata.py Balantiopteryx_io 0 0
./collectdata.py Balantiopteryx_plicata 10 6
./collectdata.py Balionycteris_maculata 17 67
./collectdata.py Cardioderma_cor 27 16
./collectdata.py Carollia_brevicauda_121 42 36
./collectdata.py Carollia_brevicauda_122 34 24
./collectdata.py Carollia_brevicauda_123 49 38
./collectdata.py Carollia_brevicauda_124 8 6
./collectdata.py Carollia_castanea 53 74
./collectdata.py Carollia_castanea_132 24 21
./collectdata.py Carollia_castanea_133 17 28
./collectdata.py Carollia_perspicillata 1067 61
./collectdata.py Carollia_sowelli_129 9 17
./collectdata.py Carollia_sowelli_130 19 15
./collectdata.py Carollia_subrufa 23 9
./collectdata.py Centronycteris_maximiliani 5 3
./collectdata.py Centurio_senex_25 29 35
./collectdata.py Centurio_senex_26 9 7
./collectdata.py Chaerephon_pumilus 10 5
./collectdata.py Chiroderma_doriae 4 3
./collectdata.py Chiroderma_trinitatum 47 23
./collectdata.py Chiroderma_villosum 60 46
./collectdata.py Choeroniscus_minor 8 1
./collectdata.py Chrotopterus_auritus 69 113
./collectdata.py Coleura_afra 21 30
./collectdata.py Cormura_brevirostris_1 25 23
./collectdata.py Cynomops_paranus 13 9
./collectdata.py Cynopterus_brachyotis 27 42
./collectdata.py Cynopterus_horsfieldii 6 19
./collectdata.py Cynopterus_sphinx 115 48
./collectdata.py Desmodus_rotundus_170 13 12
./collectdata.py Desmodus_rotundus_171 10 10
./collectdata.py Desmodus_rotundus_174 27 29
./collectdata.py Diaemus_youngi 5 4
./collectdata.py Diclidurus_isabellus 25 4
./collectdata.py Diphylla_ecaudata 3 40
./collectdata.py Eidolon_helvum 15 33
./collectdata.py Eonycteris_spelaea 19 8
./collectdata.py Epomophorus_labiatus 3 29
./collectdata.py Epomophorus_wahlbergi 8 1
./collectdata.py Eptesicus_bobrinskoi 4 3
./collectdata.py Eptesicus_chiriquinus 23 22
./collectdata.py Eptesicus_furinalis_24 17 16
./collectdata.py Eptesicus_furinalis_26 6 2
./collectdata.py Eptesicus_fuscus 8 3
./collectdata.py Eptesicus_serotinus_20 10 3
./collectdata.py Eptesicus_serotinus_21 0 0
./collectdata.py Eudiscopus_denticulus 15 5
./collectdata.py Eumops_auripendulus 7 5
./collectdata.py Eumops_hansae 10 6
./collectdata.py Furipterus_horrens 5 34
./collectdata.py Glischropus_tylopus 19 7
./collectdata.py Glossophaga_commissarisi_106 15 15
./collectdata.py Glossophaga_commissarisi_107 10 14
./collectdata.py Glossophaga_leachii 9 1
./collectdata.py Glossophaga_longirostris 39 9
./collectdata.py Glossophaga_soricina_102 27 32
./collectdata.py Glossophaga_soricina_98 101 67
./collectdata.py Glyphonycteris_daviesi 10 18
./collectdata.py Glyphonycteris_sylvestris 4 15
./collectdata.py Harpiocephalus_harpia 20 20
./collectdata.py Hesperoptenus_blanfordi 7 4
./collectdata.py Hesperoptenus_tickelli 3 4
./collectdata.py Hipposideros_armiger 45 42
./collectdata.py Hipposideros_cervinus_69 0 0
./collectdata.py Hipposideros_cervinus_73 9 11
./collectdata.py Hipposideros_cineraceus_15 8 4
./collectdata.py Hipposideros_cineraceus_61 11 3
./collectdata.py Hipposideros_commersoni 10 17
./collectdata.py Hipposideros_diadema_23 8 2
./collectdata.py Hipposideros_diadema_24 6 3
./collectdata.py Hipposideros_diadema_25 9 6
./collectdata.py Hipposideros_dyacorum 4 12
./collectdata.py Hipposideros_galeritus 18 58
./collectdata.py Hipposideros_grandis 3 2
./collectdata.py Hipposideros_khaokhouayensis 5 5
./collectdata.py Hipposideros_larvatus_67 14 1
./collectdata.py Hipposideros_larvatus_72 0 0
./collectdata.py Hipposideros_lylei 5 4
./collectdata.py Hipposideros_pomona 51 55
./collectdata.py Hipposideros_pratti 4 11
./collectdata.py Hipposideros_rotalis 7 3
./collectdata.py Hipposideros_ruber 22 102
./collectdata.py Hylonycteris_underwoodi 4 57
./collectdata.py Hypsugo_cadornae 15 1
./collectdata.py Hypsugo_pulveratus 16 11
./collectdata.py Kerivoula_hardwickii_111 13 21
./collectdata.py Kerivoula_hardwickii_113 16 77
./collectdata.py Kerivoula_intermedia_103 0 0
./collectdata.py Kerivoula_kachinensis 9 12
./collectdata.py Kerivoula_minuta 7 41
./collectdata.py Kerivoula_minuta_107 9 3
./collectdata.py Kerivoula_papillosa 10 72
./collectdata.py Kerivoula_pellucida 5 9
./collectdata.py Kerivoula_picta 3 1
./collectdata.py Kerivoula_titania 14 18
./collectdata.py Lasiurus_atratus 4 5
./collectdata.py Lasiurus_blossevillii_7 6 1
./collectdata.py Lasiurus_cinereus 25 7
./collectdata.py Lasiurus_egregius 4 6
./collectdata.py Lionycteris_spurrelli 77 40
./collectdata.py Lonchorhina_aurita 3 126
./collectdata.py Lonchorhina_inusitata 5 4
./collectdata.py Lonchorhina_orinocensis 10 9
./collectdata.py Lophostoma_brasiliense_162 13 12
./collectdata.py Lophostoma_carrikeri 11 16
./collectdata.py Lophostoma_evotis 3 2
./collectdata.py Lophostoma_schulzi 7 10
./collectdata.py Lophostoma_silvicolum_164 39 27
./collectdata.py Lophostoma_silvicolum_165 22 32
./collectdata.py Macroglossus_minimus_22 12 11
./collectdata.py Macroglossus_minimus_70 9 6
./collectdata.py Macroglossus_sobrinus 10 7
./collectdata.py Macrophyllum_macrophyllum_116 10 12
./collectdata.py Megaderma_lyra 11 1
./collectdata.py Megaderma_spasma 8 7
./collectdata.py Megaerops_niphanae 37 20
./collectdata.py Mesophylla_macconnelli 41 11
./collectdata.py Micronycteris_brachyotis 3 3
./collectdata.py Micronycteris_brosseti 4 2
./collectdata.py Micronycteris_hirsuta 9 47
./collectdata.py Micronycteris_megalotis 53 89
./collectdata.py Micronycteris_minuta_189 8 4
./collectdata.py Micronycteris_minuta_190 0 0
./collectdata.py Micronycteris_nicefori 36 56
./collectdata.py Mimon_bennettii 0 0
./collectdata.py Mimon_cozumelae 8 104
./collectdata.py Mimon_crenulatum 87 65
./collectdata.py Miniopterus_africanus 11 5
./collectdata.py Miniopterus_fuliginosus 9 10
./collectdata.py Miniopterus_inflatus 12 3
./collectdata.py Miniopterus_magnater 30 10
./collectdata.py Miniopterus_medius 3 51
./collectdata.py Miniopterus_minor 31 29
./collectdata.py Miniopterus_natalensis 17 12
./collectdata.py Miniopterus_pusillus 9 22
./collectdata.py Miniopterus_schreibersii 35 23
./collectdata.py Molossops_neglectus 11 5
./collectdata.py Molossops_temminckii 5 2
./collectdata.py Molossus_coibensis 7 3
./collectdata.py Molossus_molossus_15 23 13
./collectdata.py Molossus_molossus_16 105 33
./collectdata.py Molossus_rufus 51 60
./collectdata.py Mormoops_megalophylla 0 0
./collectdata.py Murina_aenea 3 6
./collectdata.py Murina_aurata 16 34
./collectdata.py Murina_cyclotis_132 8 12
./collectdata.py Murina_cyclotis_137 13 18
./collectdata.py Murina_cyclotis_138 17 6
./collectdata.py Murina_gracilis 96 51
./collectdata.py Murina_hilgendorfi 14 10
./collectdata.py Murina_huttoni_129 8 2
./collectdata.py Murina_huttoni_130 4 8
./collectdata.py Murina_huttoni_131 0 0
./collectdata.py Murina_leucogaster 0 0
./collectdata.py Murina_puta 211 75
./collectdata.py Murina_recondita 128 42
./collectdata.py Murina_suilla 3 28
./collectdata.py Murina_tubinaris_141 7 8
./collectdata.py Murina_tubinaris_142 9 11
./collectdata.py Murina_tubinaris_143 13 4
./collectdata.py Murina_ussuriensis 9 8
./collectdata.py Myotis_albescens 28 20
./collectdata.py Myotis_alcathoe 15 4
./collectdata.py Myotis_annamiticus 0 0
./collectdata.py Myotis_annectans 5 31
./collectdata.py Myotis_ater 9 31
./collectdata.py Myotis_aurascens 27 20
./collectdata.py Myotis_blythii_23 6 6
./collectdata.py Myotis_blythii_64 7 4
./collectdata.py Myotis_bombinus 5 4
./collectdata.py Myotis_brandtii_102 8 2
./collectdata.py Myotis_brandtii_103 9 2
./collectdata.py Myotis_brandtii_78 18 3
./collectdata.py Myotis_brandtii_98 8 2
./collectdata.py Myotis_dasycneme 8 3
./collectdata.py Myotis_daubentonii 38 47
./collectdata.py Myotis_elegans 5 7
./collectdata.py Myotis_emarginatus 4 1
./collectdata.py Myotis_evotis 8 47
./collectdata.py Myotis_frater_54 4 1
./collectdata.py Myotis_frater_55 8 4
./collectdata.py Myotis_hasseltii 14 8
./collectdata.py Myotis_horsfieldii_73 4 1
./collectdata.py Myotis_horsfieldii_74 13 6
./collectdata.py Myotis_horsfieldii_75 0 0
./collectdata.py Myotis_ikonnikovi 14 9
./collectdata.py Myotis_ikonnikovi_56 0 0
./collectdata.py Myotis_ikonnikovi_57 8 4
./collectdata.py Myotis_keaysi_101 0 0
./collectdata.py Myotis_keaysi_109 11 62
./collectdata.py Myotis_keaysi_37 6 3
./collectdata.py Myotis_laniger 26 22
./collectdata.py Myotis_lucifugus 9 60
./collectdata.py Myotis_lucifugus_alarel 8 46
./collectdata.py Myotis_lucifugus_car 5 19
./collectdata.py Myotis_lucifugus_luc 6 14
./collectdata.py Myotis_montivagus 12 5
./collectdata.py Myotis_muricola 64 105
./collectdata.py Myotis_mystacinus 16 66
./collectdata.py Myotis_nattereri 23 94
./collectdata.py Myotis_nigricans 32 95
./collectdata.py Myotis_ricketti_95 8 1
./collectdata.py Myotis_ricketti_96 0 0
./collectdata.py Myotis_riparius_113 4 5
./collectdata.py Myotis_riparius_40 0 0
./collectdata.py Myotis_riparius_62 16 22
./collectdata.py Myotis_riparius_66 4 4
./collectdata.py Myotis_rosseti 7 6
./collectdata.py Myotis_ruber 0 0
./collectdata.py Myotis_siligorensis_21 7 5
./collectdata.py Myotis_siligorensis_59 12 18
./collectdata.py Myotis_siligorensis_61 8 9
./collectdata.py Myotis_thysanodes 6 28
./collectdata.py Myotis_yumanensis 7 41
./collectdata.py Nanonycteris_veldkampii 6 8
./collectdata.py Natalus_stramineus_1 0 0
./collectdata.py Neoromicia_brunneus 3 48
./collectdata.py Neoromicia_nanus 0 0
./collectdata.py Noctilio_leporinus_3 19 16
./collectdata.py Noctilio_leporinus_4 0 0
./collectdata.py Nyctalus_leisleri 4 3
./collectdata.py Nyctalus_noctula 5 2
./collectdata.py Nycteris_hispida 0 0
./collectdata.py Nycteris_tragata 7 16
./collectdata.py Nyctinomops_laticaudatus 17 3
./collectdata.py Otomops_martiensseni 19 2
./collectdata.py Penthetor_lucasi_20 10 7
./collectdata.py Penthetor_lucasi_33 12 16
./collectdata.py Peropteryx_trinitatis 12 3
./collectdata.py Philetor_brachypterus 3 34
./collectdata.py Phoniscus_jagorii 11 16
./collectdata.py Phylloderma_stenops_156 10 38
./collectdata.py Phylloderma_stenops_else 24 47
./collectdata.py Phyllostomus_discolor 84 105
./collectdata.py Phyllostomus_elongatus 199 120
./collectdata.py Phyllostomus_latifolius 9 14
./collectdata.py Pipistrellus_abramus 21 54
./collectdata.py Pipistrellus_coromandra 29 21
./collectdata.py Pipistrellus_javanicus 19 49
./collectdata.py Pipistrellus_javanicus_67 13 13
./collectdata.py Pipistrellus_javanicus_72 7 5
./collectdata.py Pipistrellus_kuhlii_58 0 0
./collectdata.py Pipistrellus_kuhlii_59 0 0
./collectdata.py Pipistrellus_kuhlii_60 8 1
./collectdata.py Pipistrellus_nanulus 6 22
./collectdata.py Pipistrellus_nathusii 10 6
./collectdata.py Pipistrellus_paterculus 20 16
./collectdata.py Pipistrellus_pipistrellus 9 6
./collectdata.py Pipistrellus_pygmaeus 12 5
./collectdata.py Pipistrellus_tenuis 30 11
./collectdata.py Platyrrhinus_aurarius 45 14
./collectdata.py Platyrrhinus_brachycephalus 3 9
./collectdata.py Platyrrhinus_helleri_73 77 39
./collectdata.py Platyrrhinus_helleri_77 8 7
./collectdata.py Platyrrhinus_helleri_78 19 24
./collectdata.py Platyrrhinus_infuscus 30 15
./collectdata.py Platyrrhinus_recifinus 3 2
./collectdata.py Plecotus_auritus 6 3
./collectdata.py Plecotus_ognevi 28 11
./collectdata.py Promops_centralis 4 7
./collectdata.py Pteronotus_davyi 10 3
./collectdata.py Pteronotus_gymnonotus 12 41
./collectdata.py Pteronotus_parnellii 408 69
./collectdata.py Pteronotus_personatus 48 92
./collectdata.py Pteropus_lylei 6 9
./collectdata.py Rhinolophus_acuminatus_22 12 2
./collectdata.py Rhinolophus_acuminatus_23 4 1
./collectdata.py Rhinolophus_affinis_11 0 0
./collectdata.py Rhinolophus_affinis_54 30 26
./collectdata.py Rhinolophus_alcyone 6 18
./collectdata.py Rhinolophus_borneensis 13 8
./collectdata.py Rhinolophus_coelophyllus 0 0
./collectdata.py Rhinolophus_creaghi 0 0
./collectdata.py Rhinolophus_ferrumequinum 9 98
./collectdata.py Rhinolophus_hildebrandti 0 0
./collectdata.py Rhinolophus_hipposideros 367 120
./collectdata.py Rhinolophus_lepidus_31 11 12
./collectdata.py Rhinolophus_lepidus_37 9 13
./collectdata.py Rhinolophus_luctus 13 4
./collectdata.py Rhinolophus_macrotis_56 17 7
./collectdata.py Rhinolophus_malayanus 22 21
./collectdata.py Rhinolophus_marshalli 5 11
./collectdata.py Rhinolophus_monoceros 3 2
./collectdata.py Rhinolophus_paradoxolophus_16 6 1
./collectdata.py Rhinolophus_paradoxolophus_86 20 18
./collectdata.py Rhinolophus_pearsonii 106 57
./collectdata.py Rhinolophus_philippinensis 0 0
./collectdata.py Rhinolophus_pusillus 52 60
./collectdata.py Rhinolophus_rouxii 21 6
./collectdata.py Rhinolophus_shameli_41 15 3
./collectdata.py Rhinolophus_siamensis 6 10
./collectdata.py Rhinolophus_siamensis_56 9 7
./collectdata.py Rhinolophus_stheno_10 0 0
./collectdata.py Rhinolophus_stheno_28 22 2
./collectdata.py Rhinolophus_stheno_29 0 0
./collectdata.py Rhinolophus_stheno_9 4 2
./collectdata.py Rhinolophus_thomasi 69 44
./collectdata.py Rhinolophus_trifoliatus_38 14 17
./collectdata.py Rhinophylla_alethina 3 15
./collectdata.py Rhinophylla_fischerae 39 38
./collectdata.py Rhinophylla_pumilio 396 102
./collectdata.py Rhogeessa_aeneus 21 17
./collectdata.py Rhogeessa_io 0 0
./collectdata.py Rhynchonycteris_naso 96 33
./collectdata.py Rousettus_amplexicaudatus 10 20
./collectdata.py Rousettus_leschenaultii 21 12
./collectdata.py Saccopteryx_bilineata_23 62 32
./collectdata.py Saccopteryx_bilineata_33 11 7
./collectdata.py Saccopteryx_bilineata_9 12 17
./collectdata.py Saccopteryx_gymnura 3 1
./collectdata.py Saccopteryx_leptura_28 18 13
./collectdata.py Saccopteryx_leptura_37 19 21
./collectdata.py Scotomanes_ornatus 34 14
./collectdata.py Scotophilus_dinganii 0 0
./collectdata.py Scotophilus_heathii_157 7 10
./collectdata.py Scotophilus_heathii_158 0 0
./collectdata.py Scotophilus_kuhlii 16 12
./collectdata.py Sphaerias_blanfordi 21 13
./collectdata.py Sturnira_bidens 40 11
./collectdata.py Sturnira_erythromos 50 14
./collectdata.py Sturnira_lilium 34 39
./collectdata.py Sturnira_lilium_7 19 10
./collectdata.py Sturnira_lilium_8 35 18
./collectdata.py Sturnira_lilium_9 107 36
./collectdata.py Sturnira_ludovici_13 17 21
./collectdata.py Sturnira_ludovici_14 40 21
./collectdata.py Sturnira_ludovici_16 8 11
./collectdata.py Sturnira_luisi 102 17
./collectdata.py Sturnira_magna 37 16
./collectdata.py Sturnira_tildae 192 47
./collectdata.py Tadarida_brasiliensis 6 11
./collectdata.py Tadarida_teniotis 0 0
./collectdata.py Taphozous_hildegardeae 0 0
./collectdata.py Taphozous_melanopogon 0 0
./collectdata.py Thyroptera_lavali 3 13
./collectdata.py Thyroptera_tricolor 27 146
./collectdata.py Thyroptera_tricolor_2 7 5
./collectdata.py Tonatia_saurophila 75 29
./collectdata.py Tonatia_saurophila_159 8 4
./collectdata.py Tonatia_saurophila_160 18 6
./collectdata.py Trachops_cirrhosus_109 10 4
./collectdata.py Trachops_cirrhosus_110 23 76
./collectdata.py Triaenops_persicus 7 13
./collectdata.py Tylonycteris_pachypus 14 31
./collectdata.py Tylonycteris_pachypus_75 7 6
./collectdata.py Tylonycteris_pachypus_76 9 15
./collectdata.py Tylonycteris_robustula 19 118
./collectdata.py Tylonycteris_robustula_73 16 32
./collectdata.py Tylonycteris_robustula_74 6 4
./collectdata.py Tylonycteris_robustula_76 0 0
./collectdata.py Uroderma_bilobatum 134 67
./collectdata.py Uroderma_bilobatum_60 92 57
./collectdata.py Uroderma_bilobatum_61 11 17
./collectdata.py Vampyressa_bidens 144 127
./collectdata.py Vampyressa_bidens_82 11 17
./collectdata.py Vampyressa_bidens_83 78 79
./collectdata.py Vampyressa_brocki 11 15
./collectdata.py Vampyressa_nymphaea 8 8
./collectdata.py Vampyressa_pusilla 7 9
./collectdata.py Vampyressa_thyone 52 102
./collectdata.py Vampyressa_thyone_68 35 29
./collectdata.py Vampyrodes_caraccioli 73 83
./collectdata.py Vampyrodes_caraccioli_69 4 1
./collectdata.py Vampyrodes_caraccioli_70 12 4
./collectdata.py Vampyrodes_caraccioli_71 16 6
./collectdata.py Vampyrodes_caraccioli_72 6 3
./collectdata.py Vampyrum_spectrum 5 9
./collectdata.py Vespertilio_murinus 17 8
./collectdata.py Vespertilio_sinensis 4 3