#! /bin/bash

#./newbase.py Anoura_latidens 6 1
#./newbase.py Antrozous_pallidus 11 34
#./newbase.py Arielulus_aureocollaris 5 7
#./newbase.py Arielulus_circumdatus 7 3
#./newbase.py Artibeus_amplus 32 17
#./newbase.py Artibeus_anderseni 14 11
#./newbase.py Artibeus_aztecus 11 4
#./newbase.py Artibeus_cinereus 173 92
#./newbase.py Artibeus_concolor 92 99
#./newbase.py Artibeus_fimbriatus 3 10
#./newbase.py Artibeus_hartii 3 19
#./newbase.py Artibeus_jamaicensis_49 9 8
#./newbase.py Artibeus_jamaicensis_50 37 21
#./newbase.py Artibeus_jamaicensis_51 8 2
#./newbase.py Artibeus_lituratus 642 79
#./newbase.py Artibeus_obscurus 576 57
#./newbase.py Artibeus_phaeotis 62 28
#./newbase.py Artibeus_planirostris 562 82
#./newbase.py Artibeus_toltecus 27 15
#./newbase.py Aselliscus_stoliczkanus 57 122
#./newbase.py Balantiopteryx_io 0 0
#./newbase.py Balantiopteryx_plicata 10 6
#./newbase.py Balionycteris_maculata 17 67
#./newbase.py Cardioderma_cor 27 16
#./newbase.py Carollia_brevicauda_121 42 36
#./newbase.py Carollia_brevicauda_122 34 24
#./newbase.py Carollia_brevicauda_123 49 38
#./newbase.py Carollia_brevicauda_124 8 6
#./newbase.py Carollia_castanea 53 74
#./newbase.py Carollia_castanea_132 24 21
#./newbase.py Carollia_castanea_133 17 28
#./newbase.py Carollia_perspicillata 1067 61
#./newbase.py Carollia_sowelli_129 9 17
#./newbase.py Carollia_sowelli_130 19 15
#./newbase.py Carollia_subrufa 23 9
#./newbase.py Centronycteris_maximiliani 5 3
#./newbase.py Centurio_senex_25 29 35
#./newbase.py Centurio_senex_26 9 7
#./newbase.py Chaerephon_pumilus 10 5
#./newbase.py Chiroderma_doriae 4 3
#./newbase.py Chiroderma_trinitatum 47 23
#./newbase.py Chiroderma_villosum 60 46
#./newbase.py Choeroniscus_minor 8 1
#./newbase.py Chrotopterus_auritus 69 113
#./newbase.py Coleura_afra 21 30
#./newbase.py Cormura_brevirostris_1 25 23
#./newbase.py Cynomops_paranus 13 9
#./newbase.py Cynopterus_brachyotis 27 42
#./newbase.py Cynopterus_horsfieldii 6 19
#./newbase.py Cynopterus_sphinx 115 48
#./newbase.py Desmodus_rotundus_170 13 12
#./newbase.py Desmodus_rotundus_171 10 10
#./newbase.py Desmodus_rotundus_174 27 29
#./newbase.py Diaemus_youngi 5 4
#./newbase.py Diclidurus_isabellus 25 4
#./newbase.py Diphylla_ecaudata 3 40
#./newbase.py Eidolon_helvum 15 33
#./newbase.py Eonycteris_spelaea 19 8
#./newbase.py Epomophorus_labiatus 3 29
#./newbase.py Epomophorus_wahlbergi 8 1
#./newbase.py Eptesicus_bobrinskoi 4 3
#./newbase.py Eptesicus_chiriquinus 23 22
#./newbase.py Eptesicus_furinalis_24 17 16
#./newbase.py Eptesicus_furinalis_26 6 2
#./newbase.py Eptesicus_fuscus 8 3
#./newbase.py Eptesicus_serotinus_20 10 3
#./newbase.py Eptesicus_serotinus_21 0 0
#./newbase.py Eudiscopus_denticulus 15 5
#./newbase.py Eumops_auripendulus 7 5
#./newbase.py Eumops_hansae 10 6
#./newbase.py Furipterus_horrens 5 34
#./newbase.py Glischropus_tylopus 19 7
#./newbase.py Glossophaga_commissarisi_106 15 15
#./newbase.py Glossophaga_commissarisi_107 10 14
#./newbase.py Glossophaga_leachii 9 1
#./newbase.py Glossophaga_longirostris 39 9
#./newbase.py Glossophaga_soricina_102 27 32
#./newbase.py Glossophaga_soricina_98 101 67
#./newbase.py Glyphonycteris_daviesi 10 18
#./newbase.py Glyphonycteris_sylvestris 4 15
#./newbase.py Harpiocephalus_harpia 20 20
#./newbase.py Hesperoptenus_blanfordi 7 4
#./newbase.py Hesperoptenus_tickelli 3 4
#./newbase.py Hipposideros_armiger 45 42
#./newbase.py Hipposideros_cervinus_69 0 0
#./newbase.py Hipposideros_cervinus_73 9 11
#./newbase.py Hipposideros_cineraceus_15 8 4
#./newbase.py Hipposideros_cineraceus_61 11 3
#./newbase.py Hipposideros_commersoni 10 17
#./newbase.py Hipposideros_diadema_23 8 2
#./newbase.py Hipposideros_diadema_24 6 3
#./newbase.py Hipposideros_diadema_25 9 6
#./newbase.py Hipposideros_dyacorum 4 12
#./newbase.py Hipposideros_galeritus 18 58
#./newbase.py Hipposideros_grandis 3 2
#./newbase.py Hipposideros_khaokhouayensis 5 5
#./newbase.py Hipposideros_larvatus_67 14 1
#./newbase.py Hipposideros_larvatus_72 0 0
#./newbase.py Hipposideros_lylei 5 4
#./newbase.py Hipposideros_pomona 51 55
#./newbase.py Hipposideros_pratti 4 11
#./newbase.py Hipposideros_rotalis 7 3
#./newbase.py Hipposideros_ruber 22 102
#./newbase.py Hylonycteris_underwoodi 4 57
#./newbase.py Hypsugo_cadornae 15 1
#./newbase.py Hypsugo_pulveratus 16 11
#./newbase.py Kerivoula_hardwickii_111 13 21
#./newbase.py Kerivoula_hardwickii_113 16 77
#./newbase.py Kerivoula_intermedia_103 0 0
#./newbase.py Kerivoula_kachinensis 9 12
#./newbase.py Kerivoula_minuta 7 41
#./newbase.py Kerivoula_minuta_107 9 3
#./newbase.py Kerivoula_papillosa 10 72
#./newbase.py Kerivoula_pellucida 5 9
#./newbase.py Kerivoula_picta 3 1
#./newbase.py Kerivoula_titania 14 18
#./newbase.py Lasiurus_atratus 4 5
#./newbase.py Lasiurus_blossevillii_7 6 1
#./newbase.py Lasiurus_cinereus 25 7
#./newbase.py Lasiurus_egregius 4 6
#./newbase.py Lionycteris_spurrelli 77 40
#./newbase.py Lonchorhina_aurita 3 126
#./newbase.py Lonchorhina_inusitata 5 4
#./newbase.py Lonchorhina_orinocensis 10 9
#./newbase.py Lophostoma_brasiliense_162 13 12
#./newbase.py Lophostoma_carrikeri 11 16
#./newbase.py Lophostoma_evotis 3 2
#./newbase.py Lophostoma_schulzi 7 10
#./newbase.py Lophostoma_silvicolum_164 39 27
#./newbase.py Lophostoma_silvicolum_165 22 32
#./newbase.py Macroglossus_minimus_22 12 11
#./newbase.py Macroglossus_minimus_70 9 6
#./newbase.py Macroglossus_sobrinus 10 7
#./newbase.py Macrophyllum_macrophyllum_116 10 12
#./newbase.py Megaderma_lyra 11 1
#./newbase.py Megaderma_spasma 8 7
#./newbase.py Megaerops_niphanae 37 20
#./newbase.py Mesophylla_macconnelli 41 11
#./newbase.py Micronycteris_brachyotis 3 3
#./newbase.py Micronycteris_brosseti 4 2
#./newbase.py Micronycteris_hirsuta 9 47
#./newbase.py Micronycteris_megalotis 53 89
#./newbase.py Micronycteris_minuta_189 8 4
#./newbase.py Micronycteris_minuta_190 0 0
#./newbase.py Micronycteris_nicefori 36 56
#./newbase.py Mimon_bennettii 0 0
#./newbase.py Mimon_cozumelae 8 104
#./newbase.py Mimon_crenulatum 87 65
#./newbase.py Miniopterus_africanus 11 5
#./newbase.py Miniopterus_fuliginosus 9 10
#./newbase.py Miniopterus_inflatus 12 3
#./newbase.py Miniopterus_magnater 30 10
#./newbase.py Miniopterus_medius 3 51
#./newbase.py Miniopterus_minor 31 29
#./newbase.py Miniopterus_natalensis 17 12
#./newbase.py Miniopterus_pusillus 9 22
#./newbase.py Miniopterus_schreibersii 35 23
#./newbase.py Molossops_neglectus 11 5
#./newbase.py Molossops_temminckii 5 2
#./newbase.py Molossus_coibensis 7 3
#./newbase.py Molossus_molossus_15 23 13
#./newbase.py Molossus_molossus_16 105 33
#./newbase.py Molossus_rufus 51 60
#./newbase.py Mormoops_megalophylla 0 0
#./newbase.py Murina_aenea 3 6
#./newbase.py Murina_aurata 16 34
#./newbase.py Murina_cyclotis_132 8 12
#./newbase.py Murina_cyclotis_137 13 18
#./newbase.py Murina_cyclotis_138 17 6
#./newbase.py Murina_gracilis 96 51
#./newbase.py Murina_hilgendorfi 14 10
#./newbase.py Murina_huttoni_129 8 2
#./newbase.py Murina_huttoni_130 4 8
#./newbase.py Murina_huttoni_131 0 0
#./newbase.py Murina_leucogaster 0 0
#./newbase.py Murina_puta 211 75
#./newbase.py Murina_recondita 128 42
#./newbase.py Murina_suilla 3 28
#./newbase.py Murina_tubinaris_141 7 8
#./newbase.py Murina_tubinaris_142 9 11
#./newbase.py Murina_tubinaris_143 13 4
#./newbase.py Murina_ussuriensis 9 8
#./newbase.py Myotis_albescens 28 20
#./newbase.py Myotis_alcathoe 15 4
#./newbase.py Myotis_annamiticus 0 0
#./newbase.py Myotis_annectans 5 31
#./newbase.py Myotis_ater 9 31
#./newbase.py Myotis_aurascens 27 20
#./newbase.py Myotis_blythii_23 6 6
#./newbase.py Myotis_blythii_64 7 4
#./newbase.py Myotis_bombinus 5 4
#./newbase.py Myotis_brandtii_102 8 2
#./newbase.py Myotis_brandtii_103 9 2
#./newbase.py Myotis_brandtii_78 18 3
#./newbase.py Myotis_brandtii_98 8 2
#./newbase.py Myotis_dasycneme 8 3
#./newbase.py Myotis_daubentonii 38 47
#./newbase.py Myotis_elegans 5 7
#./newbase.py Myotis_emarginatus 4 1
#./newbase.py Myotis_evotis 8 47
#./newbase.py Myotis_frater_54 4 1
#./newbase.py Myotis_frater_55 8 4
#./newbase.py Myotis_hasseltii 14 8
#./newbase.py Myotis_horsfieldii_73 4 1
#./newbase.py Myotis_horsfieldii_74 13 6
#./newbase.py Myotis_horsfieldii_75 0 0
#./newbase.py Myotis_ikonnikovi 14 9
#./newbase.py Myotis_ikonnikovi_56 0 0
#./newbase.py Myotis_ikonnikovi_57 8 4
#./newbase.py Myotis_keaysi_101 0 0
#./newbase.py Myotis_keaysi_109 11 62
#./newbase.py Myotis_keaysi_37 6 3
#./newbase.py Myotis_laniger 26 22
#./newbase.py Myotis_lucifugus 9 60
#./newbase.py Myotis_lucifugus_alarel 8 46
#./newbase.py Myotis_lucifugus_car 5 19
#./newbase.py Myotis_lucifugus_luc 6 14
#./newbase.py Myotis_montivagus 12 5
#./newbase.py Myotis_muricola 64 105
#./newbase.py Myotis_mystacinus 16 66
#./newbase.py Myotis_nattereri 23 94
#./newbase.py Myotis_nigricans 32 95
#./newbase.py Myotis_ricketti_95 8 1
#./newbase.py Myotis_ricketti_96 0 0
#./newbase.py Myotis_riparius_113 4 5
#./newbase.py Myotis_riparius_40 0 0
#./newbase.py Myotis_riparius_62 16 22
#./newbase.py Myotis_riparius_66 4 4
#./newbase.py Myotis_rosseti 7 6
#./newbase.py Myotis_ruber 0 0
#./newbase.py Myotis_siligorensis_21 7 5
#./newbase.py Myotis_siligorensis_59 12 18
./newbase.py Myotis_siligorensis_61 8 9
./newbase.py Myotis_thysanodes 6 28
./newbase.py Myotis_yumanensis 7 41
./newbase.py Nanonycteris_veldkampii 6 8
#./newbase.py Natalus_stramineus_1 0 0
./newbase.py Neoromicia_brunneus 3 48
#./newbase.py Neoromicia_nanus 0 0
./newbase.py Noctilio_leporinus_3 19 16
#./newbase.py Noctilio_leporinus_4 0 0
./newbase.py Nyctalus_leisleri 4 3
./newbase.py Nyctalus_noctula 5 2
#./newbase.py Nycteris_hispida 0 0
./newbase.py Nycteris_tragata 7 16
./newbase.py Nyctinomops_laticaudatus 17 3
./newbase.py Otomops_martiensseni 19 2
./newbase.py Penthetor_lucasi_20 10 7
./newbase.py Penthetor_lucasi_33 12 16
./newbase.py Peropteryx_trinitatis 12 3
./newbase.py Philetor_brachypterus 3 34
./newbase.py Phoniscus_jagorii 11 16
./newbase.py Phylloderma_stenops_156 10 38
./newbase.py Phylloderma_stenops_else 24 47
./newbase.py Phyllostomus_discolor 84 105
./newbase.py Phyllostomus_elongatus 199 120
./newbase.py Phyllostomus_latifolius 9 14
./newbase.py Pipistrellus_abramus 21 54
./newbase.py Pipistrellus_coromandra 29 21
./newbase.py Pipistrellus_javanicus 19 49
./newbase.py Pipistrellus_javanicus_67 13 13
./newbase.py Pipistrellus_javanicus_72 7 5
#./newbase.py Pipistrellus_kuhlii_58 0 0
#./newbase.py Pipistrellus_kuhlii_59 0 0
#./newbase.py Pipistrellus_kuhlii_60 8 1
#./newbase.py Pipistrellus_nanulus 6 22
#./newbase.py Pipistrellus_nathusii 10 6
#./newbase.py Pipistrellus_paterculus 20 16
#./newbase.py Pipistrellus_pipistrellus 9 6
#./newbase.py Pipistrellus_pygmaeus 12 5
#./newbase.py Pipistrellus_tenuis 30 11
#./newbase.py Platyrrhinus_aurarius 45 14
#./newbase.py Platyrrhinus_brachycephalus 3 9
#./newbase.py Platyrrhinus_helleri_73 77 39
#./newbase.py Platyrrhinus_helleri_77 8 7
#./newbase.py Platyrrhinus_helleri_78 19 24
#./newbase.py Platyrrhinus_infuscus 30 15
#./newbase.py Platyrrhinus_recifinus 3 2
#./newbase.py Plecotus_auritus 6 3
#./newbase.py Plecotus_ognevi 28 11
#./newbase.py Promops_centralis 4 7
#./newbase.py Pteronotus_davyi 10 3
#./newbase.py Pteronotus_gymnonotus 12 41
#./newbase.py Pteronotus_parnellii 408 69
#./newbase.py Pteronotus_personatus 48 92
#./newbase.py Pteropus_lylei 6 9
#./newbase.py Rhinolophus_acuminatus_22 12 2
#./newbase.py Rhinolophus_acuminatus_23 4 1
#./newbase.py Rhinolophus_affinis_11 0 0
#./newbase.py Rhinolophus_affinis_54 30 26
#./newbase.py Rhinolophus_alcyone 6 18
#./newbase.py Rhinolophus_borneensis 13 8
#./newbase.py Rhinolophus_coelophyllus 0 0
#./newbase.py Rhinolophus_creaghi 0 0
#./newbase.py Rhinolophus_ferrumequinum 9 98
#./newbase.py Rhinolophus_hildebrandti 0 0
#./newbase.py Rhinolophus_hipposideros 367 120
#./newbase.py Rhinolophus_lepidus_31 11 12
#./newbase.py Rhinolophus_lepidus_37 9 13
#./newbase.py Rhinolophus_luctus 13 4
#./newbase.py Rhinolophus_macrotis_56 17 7
#./newbase.py Rhinolophus_malayanus 22 21
#./newbase.py Rhinolophus_marshalli 5 11
#./newbase.py Rhinolophus_monoceros 3 2
#./newbase.py Rhinolophus_paradoxolophus_16 6 1
#./newbase.py Rhinolophus_paradoxolophus_86 20 18
#./newbase.py Rhinolophus_pearsonii 106 57
#./newbase.py Rhinolophus_philippinensis 0 0
#./newbase.py Rhinolophus_pusillus 52 60
#./newbase.py Rhinolophus_rouxii 21 6
#./newbase.py Rhinolophus_shameli_41 15 3
#./newbase.py Rhinolophus_siamensis 6 10
#./newbase.py Rhinolophus_siamensis_56 9 7
#./newbase.py Rhinolophus_stheno_10 0 0
#./newbase.py Rhinolophus_stheno_28 22 2
#./newbase.py Rhinolophus_stheno_29 0 0
#./newbase.py Rhinolophus_stheno_9 4 2
#./newbase.py Rhinolophus_thomasi 69 44
#./newbase.py Rhinolophus_trifoliatus_38 14 17
#./newbase.py Rhinophylla_alethina 3 15
#./newbase.py Rhinophylla_fischerae 39 38
#./newbase.py Rhinophylla_pumilio 396 102
#./newbase.py Rhogeessa_aeneus 21 17
#./newbase.py Rhogeessa_io 0 0
#./newbase.py Rhynchonycteris_naso 96 33
#./newbase.py Rousettus_amplexicaudatus 10 20
#./newbase.py Rousettus_leschenaultii 21 12
#./newbase.py Saccopteryx_bilineata_23 62 32
#./newbase.py Saccopteryx_bilineata_33 11 7
#./newbase.py Saccopteryx_bilineata_9 12 17
#./newbase.py Saccopteryx_gymnura 3 1
#./newbase.py Saccopteryx_leptura_28 18 13
#./newbase.py Saccopteryx_leptura_37 19 21
#./newbase.py Scotomanes_ornatus 34 14
#./newbase.py Scotophilus_dinganii 0 0
#./newbase.py Scotophilus_heathii_157 7 10
#./newbase.py Scotophilus_heathii_158 0 0
#./newbase.py Scotophilus_kuhlii 16 12
#./newbase.py Sphaerias_blanfordi 21 13
#./newbase.py Sturnira_bidens 40 11
#./newbase.py Sturnira_erythromos 50 14
#./newbase.py Sturnira_lilium 34 39
#./newbase.py Sturnira_lilium_7 19 10
#./newbase.py Sturnira_lilium_8 35 18
#./newbase.py Sturnira_lilium_9 107 36
#./newbase.py Sturnira_ludovici_13 17 21
#./newbase.py Sturnira_ludovici_14 40 21
#./newbase.py Sturnira_ludovici_16 8 11
#./newbase.py Sturnira_luisi 102 17
#./newbase.py Sturnira_magna 37 16
#./newbase.py Sturnira_tildae 192 47
#./newbase.py Tadarida_brasiliensis 6 11
#./newbase.py Tadarida_teniotis 0 0
#./newbase.py Taphozous_hildegardeae 0 0
#./newbase.py Taphozous_melanopogon 0 0
#./newbase.py Thyroptera_lavali 3 13
#./newbase.py Thyroptera_tricolor 27 146
#./newbase.py Thyroptera_tricolor_2 7 5
#./newbase.py Tonatia_saurophila 75 29
#./newbase.py Tonatia_saurophila_159 8 4
#./newbase.py Tonatia_saurophila_160 18 6
#./newbase.py Trachops_cirrhosus_109 10 4
#./newbase.py Trachops_cirrhosus_110 23 76
#./newbase.py Triaenops_persicus 7 13
#./newbase.py Tylonycteris_pachypus 14 31
#./newbase.py Tylonycteris_pachypus_75 7 6
#./newbase.py Tylonycteris_pachypus_76 9 15
#./newbase.py Tylonycteris_robustula 19 118
#./newbase.py Tylonycteris_robustula_73 16 32
#./newbase.py Tylonycteris_robustula_74 6 4
#./newbase.py Tylonycteris_robustula_76 0 0
#./newbase.py Uroderma_bilobatum 134 67
#./newbase.py Uroderma_bilobatum_60 92 57
#./newbase.py Uroderma_bilobatum_61 11 17
#./newbase.py Vampyressa_bidens 144 127
#./newbase.py Vampyressa_bidens_82 11 17
#./newbase.py Vampyressa_bidens_83 78 79
#./newbase.py Vampyressa_brocki 11 15
#./newbase.py Vampyressa_nymphaea 8 8
#./newbase.py Vampyressa_pusilla 7 9
#./newbase.py Vampyressa_thyone 52 102
#./newbase.py Vampyressa_thyone_68 35 29
#./newbase.py Vampyrodes_caraccioli 73 83
#./newbase.py Vampyrodes_caraccioli_69 4 1
#./newbase.py Vampyrodes_caraccioli_70 12 4
#./newbase.py Vampyrodes_caraccioli_71 16 6
#./newbase.py Vampyrodes_caraccioli_72 6 3
#./newbase.py Vampyrum_spectrum 5 9
#./newbase.py Vespertilio_murinus 17 8
#./newbase.py Vespertilio_sinensis 4 3